# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------ #
# cir_rx #
# ------ #

@rp2.asm_pio(out_shiftdir=rp2.PIO.SHIFT_RIGHT)
def cir_rx():
    wrap_target()
    wait(0, pin, 0)                  [31] # 0
    nop()                            [31] # 1
    irq(rel(0))                           # 2
    label("3")
    set(x, 8)                             # 3
    set(y, 0)                             # 4
    label("5")
    mov(osr, invert(pins))           [30] # 5
    jmp(not_y, "9")                  [30] # 6
    jmp(x_dec, "5")                       # 7
    jmp("11")                             # 8
    label("9")
    out(y, 1)                             # 9
    jmp(x_dec, "5")                       # 10
    label("11")
    jmp(not_y, "13")                      # 11
    jmp("3")                              # 12
    label("13")
    irq(rel(0))                           # 13
    wrap()


